---@class WhichPy.Lsp.Handler
---@field set_python_path fun(self: WhichPy.Lsp.Handler, client: vim.lsp.Client, python_path: string)
---@field snapshot_settings fun(self: WhichPy.Lsp.Handler, client: vim.lsp.Client)
---@field restore_snapshot fun(self: WhichPy.Lsp.Handler, client: vim.lsp.Client)
